### ISSUE TITLE
mismatched choices on this page - properties say "data", example says  "delta"

### ISSUE THREAD

**Issue by seeit360** [MicrosoftDocs/minecraft-creator#543] opened 2023-01-17 07:32 UTC
"play_effect":{
    "delta" : 0,
    "effect" : "particle_sparks",
    "target" : {"test": "random_chance", "value": "3"} //25%
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab8767cb-f75f-d3fd-b536-fc90b6374583
* Version Independent ID: 88d1622f-2471-241d-bdd8-914dc958f894
* Content: [Block Documentation - play_effect](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockevents/minecraftblock_play_effect)
* Content Source: [creator/Reference/Content/BlockReference/Examples/BlockEvents/minecraftBlock_play_effect.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/BlockReference/Examples/BlockEvents/minecraftBlock_play_effect.md)
* Product: **gaming**
* GitHub Login: @mammerla
* Microsoft Alias: **mikeam**

**Comment by kakinnun** [comment] 2023-02-03 23:24
Duplicate of https://github.com/MicrosoftDocs/minecraft-creator/issues/547

**Closed by kakinnun** 2023-02-03 23:24 UTC
