### ISSUE TITLE
Errors in Actor Storage in Minecraft: Bedrock Edition

### ISSUE THREAD

**Issue by reedacartwright** [MicrosoftDocs/minecraft-creator#312] opened 2022-04-23 21:31 UTC
When reading the new documentation for [Actor Storage](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Documents/ActorStorage.md) I noticed several errors in the documentation. I've confirmed these errors by analyzing the leveldb keys in a 1.18.30 world

- "Before version 1.18.3" should be "Before version 1.18.30"
- Overworld chunk keys don't have a dimension id in them. This *is* a legacy format, but is still present in 1.18.12. As far as I can tell, it is still present in 1.18.30 and overworld chunk keys are not being upgraded to include the dimension id.
- The prefix for Actor Digest Key Space is `digp` not `dg`. 
- The prefix for Actor Keys is `actorprefix` not `actorpref`.
- Keys are stored in lexographical order in leveldb. Longer keys are not sorted separately from shorter keys. Actor Digest keys are sorted after Actor Keys in the db not before because `d` comes after `a`.
- Chunk Data is not stored contiguously in the leveldb because chunkdata doesn't have a prefix. Some chunks are stored before actor keys and digest keys. Some are stored after it.
- Chunk Data Key ID 63 isn't described.

**Comment by JDHeaden** [comment] 2022-05-07 15:38
Thank you for the feedback! I am updating the document where I can and putting a reason why if I'm not. 

- "Before version 1.18.3" should be "Before version 1.18.30" - **Done**

- Overworld chunk keys don't have a dimension id in them. This is a legacy format, but is still present in 1.18.12. As far as I can tell, it is still present in 1.18.30 and overworld chunk keys are not being upgraded to include the dimension id.

**Response: "They are right but that is as intended. We can't upgrade overworld chunk keys to include a dimension ID at the moment without breaking legacy worlds."**

- The prefix for Actor Digest Key Space is digp not dg.  - **Done**

- The prefix for Actor Keys is actorprefix not actorpref.  - **Done**

- Keys are stored in lexographical order in leveldb. Longer keys are not sorted separately from shorter keys. Actor Digest keys are sorted after Actor Keys in the db not before because d comes after a.

This one is being researched further at the moment - doc will be updated as needed. (5/6/2022)

- Chunk Data is not stored contiguously in the leveldb because chunkdata doesn't have a prefix. Some chunks are stored before actor keys and digest keys. Some are stored after it.

This one is also being researched further at the moment - doc will be updated as needed. (5/6/2022)

- Chunk Data Key ID 63 isn't described.  - **Done**

**Comment by reedacartwright** [comment] 2022-05-07 23:34
Thank you. Now that I've worked with 1.18.30 a bit more, I'm pretty sure the keys `digp` and `actorprefix` were chosen in part to prevent collsions with chunk data. That is their length is important. Any key that is 9, 10, 13, or 14 bytes long can be mistaken for chunk data. I think that is why the length of the prefix is important.

**Comment by JDHeaden** [comment] 2022-08-16 14:09
I'm going to go ahead and close this for now. If I get more information about these, I will make more updates. Thank you for the help!

**Closed by JDHeaden** 2022-08-16 14:09 UTC
