### ISSUE TITLE
Singletons make new instances on import

### ISSUE THREAD

**Issue by kbaker4v** [MicrosoftDocs/minecraft-creator#353] opened 2022-06-09 03:14 UTC
Considering:
```

class Singleton
{
    private static _instance: Singleton;
    private stuff: string[];
    constructor()
    {
        this.stuff = [];
    }

    public static get Instance()
    {
        return this._instance || (this._instance = new this());
    }

    public add(text: string) {
        this.stuff.push(text);
    }

    public list(): string {
        return this.stuff.join('|');
    }
}

export const SingletonInstance = Singleton.Instance;
```

Before 1.19, if this was imported into 2 separate modules, it would be the same instance. However, now in 1.19, the same code always creates new instances. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b392d86-8199-5081-07fe-8852b494883f
* Version Independent ID: ed92b970-1f98-e573-7343-1d9e7d729f7b
* Content: [mojang-minecraft Module](https://docs.microsoft.com/en-us/minecraft/creator/scriptapi/mojang-minecraft/mojang-minecraft)
* Content Source: [creator/ScriptAPI/mojang-minecraft/mojang-minecraft.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/ScriptAPI/mojang-minecraft/mojang-minecraft.md)
* Product: **gaming**
* GitHub Login: @JakeShirley
* Microsoft Alias: **jashir**

**Comment by depressed-pho** [comment] 2022-07-30 06:22
This not only affects singleton classes, but affects classes in general. That is, class constructor objects are separately created for each path of module imports, so `instanceof` gives us false negatives:

```javascript
// foo.js
export class Foo {
    constructor() {}
}
```

```javascript
// bar.js
import { Foo } from "./foo.js";

export function createFoo() {
    return new Foo();
}
```

```javascript
// baz.js
import { Foo } from "./foo.js";
import { createFoo } from "./bar.js";

function baz() {
    let foo = createFoo();
    return foo instanceof Foo; // returns false!
}
```

**Comment by depressed-pho** [comment] 2022-09-12 09:58
This has become even more problematic since WatchDog has been introduced. I have an add-on consisting of 60 javascript modules, which is now impossible to load because every `import` statement now loads a module without caching it and eventually exceeds the time while loading the same module over and over again.

**Comment by ConsoleTerm** [comment] 2022-10-20 20:28
This is not problem for Script Engine but for ES at all, just by sure u dont import with .js or without, u have to import with .js only without is for TS. Can be tagged as closed issue.

**Comment by depressed-pho** [comment] 2022-11-08 14:22
Okay... I confirmed that importing modules with the prefix ".js" solves the issue. That is, the scripting engine **does** cache modules if you do this:
```javascript
import { ... } from "./foo/bar/baz.js";
```
But it doesn't if:
```javascript
import { ... } from "./foo/bar/baz";
```

Although there is a workaround, I still think the scripting engine should either disallow importing modules without ".js", or should cache modules even when they are imported without ".js". The current behavior is a confusing pitfall.

**Comment by ThomasOrs** [comment] 2023-07-18 18:25
CC @mammerla for the above as no one is assigned to this issue.

**Closed** 2023-10-11 20:06 UTC
Labels: GameTest/Scripting
