### ISSUE TITLE
minecraft:damage_sensor: Missing list of causes (missing from MS Docs entirely)

### ISSUE THREAD

**Issue by SirLich** [MicrosoftDocs/minecraft-creator#98] opened 2021-07-17 19:34 UTC
[The list of damage causes can be found here, on Bedrock.dev.](https://bedrock.dev/docs/stable/Addons#Entity%20Damage%20Source)

This should most likely be placed in its own page. 

Once written, it needs to be linked on this page, for example like this:

<html><body>

cause | none | String | Type of damage that triggers the events. [List of causes](https://bedrock.dev/docs/stable/Addons#Entity%20Damage%20Source).
-- | -- | -- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9508d013-e181-fe37-cd9f-c1ee229b1575
* Version Independent ID: a8a78e2a-3fb7-6a67-2e44-76e6346d0c38
* Content: [minecraft:damage_sensor](https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_damage_sensor)
* Content Source: [creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_damage_sensor.md](https://github.com/MicrosoftDocs/minecraft-creator/blob/main/creator/Reference/Content/EntityReference/Examples/EntityComponents/minecraftComponent_damage_sensor.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**

**Comment by v-josjones** [comment] 2021-08-03 17:59
Will be addressed as a part of our `Addons` Reference documentation.

**Comment by JDHeaden** [comment] 2022-08-24 18:57
Current version of https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_damage_sensor has a working link to the causes listed on the reference page: https://docs.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonentities#entity-damage-source

I am closing this issue for now. If this fix is not adequate, please feel free to open this issue again. Thank you, @SirLich!

**Closed by JDHeaden** 2022-08-24 18:57 UTC
Labels: Addressed
