### ISSUE TITLE
[Gametest] Inconsistency in getting locations

### ISSUE THREAD

**Issue by amon28** [MicrosoftDocs/minecraft-creator#110] opened 2021-08-12 00:35 UTC
**Describe the bug**
I am getting the player location and want to teleport to it but for some reason it teleports me to the wrong location.

**To Reproduce**
        `let loc = player.location;
        let pName = player.name;
        let gx = Math.floor(loc.x)+1;
        let gz = Math.floor(loc.z)+1;           
        try{
        Minecraft.Commands.run(`execute @a[name="${pName}"] ~ ~ ~ tp ${gx} ~ ${gz}`);
        }catch(e){
        Minecraft.Commands.run(`say ${e}`);
        }`                

**Expected behavior**
I am teleporting from my location (7,70,-6) I should be teleporting to (8,70,-5) but instead sometimes I was teleported to (0.50,70,4.50) or (1.50,70,4.50) 

**Screenshots**
![image](https://user-images.githubusercontent.com/22851168/129120523-a1a216de-0d6b-4728-ac61-25a308f52057.png)

**Additional context**
I noticed the x-axis only has this problem.

**Comment by v-josjones** [comment] 2021-08-12 23:20
I will forward this to the Gametest team to see if they can reproduce it on their end and what steps they will recommend.

**Comment by JakeShirley** [comment] 2021-08-16 22:20
@sereilly Maybe this is related to the odd player positioning stuff.

**Comment by sereilly** [comment] 2021-08-17 00:57
It's caused by a bug where player.location occasionally returns incorrect values. It should be fixed in the latest beta.

**Comment by mammerla** [comment] 2021-09-20 18:55
Should be fixed in updated builds.

**Closed** 2021-09-20 18:55 UTC
